# generated by datamodel-codegen:
#   filename:  CompletionRecord.json
#   timestamp: 2023-09-16T15:37:39+00:00

from __future__ import annotations

from pydantic import BaseModel


class CompletionRecord(BaseModel):
    time: int
    note: str
