# generated by datamodel-codegen:
#   filename:  CompletionRecord.json

from __future__ import annotations

from pydantic import BaseModel


class CompletionRecord(BaseModel):
    time: int
    note: str
