# generated by datamodel-codegen:
#   filename:  DailyTask.json
#   timestamp: 2023-09-16T15:37:41+00:00

from __future__ import annotations

from pydantic import BaseModel


class DailyTask(BaseModel):
    id: int
    taskName: str
    taskDes: str
