# generated by datamodel-codegen:
#   filename:  Login.json
#   timestamp: 2023-09-16T15:37:42+00:00

from __future__ import annotations

from pydantic import BaseModel


class Login(BaseModel):
    username: str
    password: str
