# generated by datamodel-codegen:
#   filename:  Token.json
#   timestamp: 2023-09-16T15:37:43+00:00

from __future__ import annotations

from pydantic import BaseModel


class Token(BaseModel):
    uid: int
    token: str
