# generated by datamodel-codegen:
#   filename:  TokenPayload.json
#   timestamp: 2023-09-16T15:37:44+00:00

from __future__ import annotations

from pydantic import BaseModel


class TokenPayload(BaseModel):
    sub: int
