# generated by datamodel-codegen:
#   filename:  User.json
#   timestamp: 2023-09-16T15:37:45+00:00

from __future__ import annotations

from pydantic import BaseModel


class User(BaseModel):
    uid: int
    username: str
    user_type: int
    create_time: int
